version: 1

stages:
  - id: fmt
    script: |
      go fmt github.com/srevinsaju/togomak/...

  - id: vet
    script: |
      go vet github.com/srevinsaju/togomak/...

  - id: git-provider
    script: |
      go build -v -o ./.togomak/plugins/togomak-provider-git github.com/srevinsaju/togomak/plugins/git

  - id: build
    script: |
      go build -v -o ./cmd/togomak/togomak github.com/srevinsaju/togomak/cmd/togomak 

  - id: install
    condition: true
    depends-on:
      - build
    script: |
      go install github.com/srevinsaju/togomak/cmd/togomak
  
